title: RBC iCrew User Guide
description: A hands on how to for RBC captains and members to use iCrew
theme: just-the-docs

url: https://wdrescher.github.io/rbc-icrew-doc.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
